### ISSUE TITLE
exec SP

### ISSUE THREAD

**Issue by AmirHeydari66** [ziaa/SqlPersianDateDimension#3]
Hi Dear ziaa, execution SP has problem.

**Comment by AmirHeydari66** [comment]
Hi, 
problem has been resolved. 
thanks

**Comment by ziaa** [comment]
@AmirHeydari66 
سلام،
برای استفاده سایر افراد، ممنون میشم اگه بفرمایید مشکل چی بود و چه طور حل شد؟
